# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Spot' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Spot

  pod 'Zip', :git => 'https://github.com/Workshed/Zip.git'
  pod 'Spot', :path => '../'

  target 'SpotTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
